### PR TITLE
Added Headless

### PR DESCRIPTION
**Pull request by ritikjain51**

### CODE REVIEW

**Review by gunesacar — CHANGES_REQUESTED** [review]
Hey @ritikjain51,
This PR looks good to me except a few minor styling nits (see the comments).

Currently Firefox doesn't support WebGL in headless mode (https://bugzilla.mozilla.org/show_bug.cgi?id=1375585), which we should note in the README. I can take care of that once I merge your PR.

**Comment by ritikjain51** [comment]
> Hey @ritikjain51,
> This PR looks good to me except a few minor styling nits (see the comments).
> 
> Currently Firefox doesn't support WebGL in headless mode (https://bugzilla.mozilla.org/show_bug.cgi?id=1375585), which we should note in the README. I can take care of that once I merge your PR.

**Comment by ritikjain51** [comment]
I have fixed those styling issues. 
For WebGL support, We can enable systems with `pyvirtualdisplay` If the user using Linux/Mac as a platform. 
This will enable a headless experience with WebGL support.

**Comment by gunesacar** [comment]
Merged. Thanks, @ritikjain51.

**Pull request merged**
