### PR TITLE
windows

### PR DESCRIPTION
**Pull request by kjmcgrinder**
Just had to make some minor changes and now this works on my windows machine, so I figured I should let the repository owner know.

### CODE REVIEW

**Comment by muhendis80** [comment]
i did every changes but not getting this error
"tbselenium.exceptions.TBDriverPortError: SOCKS port 9050 is not listening"
what should i do?

**Comment by kjmcgrinder** [comment]
Make sure that you are using the right versions of tor browser, selenium and geckodriver. If you are, try using the socks_port argument to use a different port. I also made those modifications 7 months ago so they may not work on the most recent version of tbselenium.

**Comment by gunesacar** [comment]
@kjmcgrinder Sorry, I couldn't respond earlier to this PR. I may be interested in merging your code, but first you'll need to rebase your code and put Windows-specific code behind an if clause like `if os.name == 'nt'`

**Comment by kjmcgrinder** [comment]
@gunesacar no worries, I'll see if I can make it a little cleaner so that it can run on windows **_OR_** linux when I get a chance and make a new pull request with the most recent commit.

**Pull request closed without merging**
