### PR TITLE
Adds utility function to set TBB security level

### PR DESCRIPTION
**Pull request by zenmonkeykstop**
Adds a function to update the preference for the security slider.

### CODE REVIEW

**Review by gunesacar — CHANGES_REQUESTED** [review]
@zenmonkeykstop, thanks for the pull request. Happy to know that the library is still being used in SecureDrop tests.

I really wanted to have this feature in the past, so this PR was spot on.

I may, however, request a change, which may help avoid potential future flakiness due to interacting with interface elements. 

I recently found out that there's a way to set Firefox preferences at runtime using chrome privileges: https://github.com/WPO-Foundation/wptagent/blob/75eba10da4052073a16777ff359d2b6870bcb280/internal/firefox_webdriver.py#L81-L100

I verified that this work with Tor Browser and tbselenium; i.e. the pref changes immediately take effect.

So, you can add a `set_pref_at_runtime(driver, key, value)` utility method based on the above code, and change your `set_security_level` to use it under the hood; e.g.:
`set_pref_at_runtime(driver, "extensions.torbutton.security_slider", level)`.

Let me know if you are interested making this change, otherwise I could add the utility method myself and ask you to rebase.

Thanks so much.

**Comment by zenmonkeykstop** [comment]
That sounds a lot cleaner, would be happy to make the change, but will probably be the weekend before I can look at it. If' that doesn't work timewise for you, go ahead and I'll just rebase.

**Comment by gunesacar** [comment]
Sure, please take your time. I wouldn't be able to get to it any sooner.

Just FYI, I plan to make a new release after merging your PR.

**Comment by zenmonkeykstop** [comment]
Hey @gunesacar, requested changes are in, along with a few tests.

**Review by gunesacar — APPROVED** [review]
Thank you @zenmonkeykstop , especially for the tests.

The highest security setting test [fails with TBB 10.0 and 10.5a1](https://travis-ci.org/github/webfp/tor-browser-selenium/builds/736669109), but works with 10.0.1 and  10.0.2.

I'm going to assume that the underlying issue is fixed and will keep testing it with the upcoming releases.

**Pull request merged**
