### PR TITLE
Update on Basic Windows Functionality Added PR

### PR DESCRIPTION
**Pull request by amoh-godwin**

### CODE REVIEW

**Comment by gunesacar** [comment]
Please take a note of my comment from the original PR:
https://github.com/webfp/tor-browser-selenium/pull/126#issuecomment-598436846
We need CI tests for the Windows-specific code. That's a hard requirement for me.
https://docs.travis-ci.com/user/reference/windows/

**Comment by amoh-godwin** [comment]
@gunesacar Ok, I will add the tests

**Comment by amoh-godwin** [comment]
@gunesacar I am on it, but I run out of credits on Travis. I have written to them to favour me with OSS credits but haven't heard back from them after that, so I have decided to switch to Circle CI or Appveyor, this is why there is a delay.
Please bear with me a little bit longer

**Comment by gunesacar** [comment]
> @gunesacar I am on it, but I run out of credits on Travis. I have written to them to favour me with OSS credits but haven't heard back from them after that, so I have decided to switch to Circle CI or Appveyor, this is why there is a delay.
> Please bear with me a little bit longer

No worries. There is no rush.

**Pull request closed without merging**
