### PR TITLE
Add support for selenium 3 and Tor Browser 7.X versions

### PR DESCRIPTION
**Pull request by gunesacar**

### CODE REVIEW

**Comment by gunesacar** [comment]
Hey @mjuarezm , I'd appreciate if you can review the changes.

**Comment by mjuarezm** [comment]
@gunesacar thanks for the PR! I have skimmed over the changes and couldn't see anything weird.

On a side note, I used the [tbgeckodriver branch](https://github.com/gunesacar/tor-browser-selenium/tree/tbgeckodriver) with tor-browser-crawler for a large crawl. Unfortunately, the crawler was freezing every now and then. I could not find cause of the freezes, though. It's a very obscure bug: it freezes in random points of the execution flow, there are no errors or exceptions, the other processes (tor and Firefox) are still running when the crawler freezes and keep logging info messages, and I can't reproduce it consistently. I think the problem stems from the communication between selenium and the browser but I couldn't trace it to a specific part of the source code. I must say I was using a modified tor so, that could also be the source of the problem. I'm afraid I need more testing to be able to give you more details about this.

**Comment by gunesacar** [comment]
Thanks, @mjuarezm , I think it's a good idea to run long crawls to test the stability.

I can imagine things being more fragile in this version with all of selenium, geckodriver and Tor Browser need to work together nicely. Let's see...

**Comment by gunesacar** [comment]
> On a side note, I used the tbgeckodriver branch with tor-browser-crawler for a large crawl. Unfortunately, the crawler was freezing every now and then. I could not find cause of the freezes, though. It's a very obscure bug: it freezes in random points of the execution flow, there are no errors or exceptions, the other processes (tor and Firefox) are still running when the crawler freezes and keep logging info messages, and I can't reproduce it consistently. I think the problem stems from the communication between selenium and the browser but I couldn't trace it to a specific part of the source code. I must say I was using a modified tor so, that could also be the source of the problem. I'm afraid I need more testing to be able to give you more details about this.

@mjuarezm I fixed an important bug that caused similar stability problems for me since we switched to selenium 3. Let me know if you run into similar problems with the new code as well.

The problem was, we were not enabling geckodriver (thanks to missing webdriver/geckodriver documentation :)
https://github.com/webfp/tor-browser-selenium/blob/master/tbselenium/tbdriver.py#L272

**Pull request merged**
